### ISSUE TITLE
batch_run for sugarscape_g1mt doesn't work (stalls, no progress)

### ISSUE THREAD

**Issue by dylan-munson** [projectmesa/mesa-examples#126]
Bug: The batch_run for sugarscape_g1mt does not seem to run.  For me, even with a very low number of steps and iterations, the process simply starts and never stops.  I was experiencing this issue with the money model example as well, but this was fixed once I downgraded to mesa 2.3.0.  The sugarscape issue persists, however, and I'm wondering if it is related to issue #76 , since it seems this model hasn't been checked yet for version issues.

Is anyone else able to reproduce this issue?

**Comment by dylan-munson** [comment]
Just an update: this issue persists in mesa 2.3.1.

**Comment by EwoutH** [comment]
Thanks for reporting this issue, and sorry for the lack of reply on your first report. 

@rht are you able to take a look at this? Otherwise I will try (but that will be in two or three weeks).

**Comment by rht** [comment]
I have this issue in my open browser tabs for a while, but haven't had the time to respond yet.

**Comment by rht** [comment]
After a quick investigation, where setting the `batch_run` `max_steps` to 10, on this line https://github.com/projectmesa/mesa/blob/d2348e2902bc6a50496d03260292216e3ae76fc9/mesa/batchrunner.py#L135, the `model.schedule.steps` is stuck at 10 after the first complete iteration. And then the actual steps blow up to beyond 10k if you wait long enough.

This should be a high priority bug to investigate, as I'm sure it affects other models as well.

**Comment by rht** [comment]
@dylan-munson sorry for the late response. https://github.com/projectmesa/mesa/pull/2183 should fix it. I have tested locally.

**Comment by dylan-munson** [comment]
No problem, thanks @rht for getting to this so quickly.  If I want to be able to use the batch run functionality at the moment, should I just install the branch from that pull request on your github?  Or would it be better to wait until this is merged into the main github branch for mesa?  Not super urgent so I can wait a few days if needed.

**Comment by rht** [comment]
If you are patient, waiting is easier. I actually haven't added a test case that reproduces this bug, etc. You could also downgrade to Mesa 2.2 or 2.1, before many WIP features were introduced.

**Comment by dylan-munson** [comment]
Thanks, I will wait for a bit for an update on a merge before proceeding.

**Comment by EwoutH** [comment]
Fixed by https://github.com/projectmesa/mesa/pull/2183!

**Comment by EwoutH** [comment]
We just released Mesa 2.3.2 which includes this fix. You can install it as usual by running 
```
pip install mesa --upgrade
```
