### ISSUE TITLE
Unable to run Schelling experimental - jupyter_viz not found 

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa-examples#145]
I am getting the following error while trying to run `examples/schelling_experimental` : 
```
from mesa.visualization.jupyter_viz import JupyterViz, Slider, make_text
ModuleNotFoundError: No module named 'mesa.visualization.jupyter_viz'
```

Steps to recreate: 
* Setup new env 
* in the examples/schelling_experimental. Run:
 `pip install -r requirements`
* run `solara run app.py`, error appears during the loading process.

**Comment by jackiekazil** [comment]
@rht, I haven't had a chance to dig into this. Am I imagining that worked on something relating to this recently? Wondering if something minor didn't get updated in versions or if this is a bigger issue?

**Comment by EwoutH** [comment]
What Python and Mesa versions are reported?

**Comment by rht** [comment]
It is `mesa~=2.0`. It is due to this PR https://github.com/projectmesa/mesa-examples/pull/128/files, which forgot to update to the latest 'pre' version for the requirements.txt.

**Comment by EwoutH** [comment]
So it should work on the latest pre-release / git main.

This is another argument why we need a monorepo (see https://github.com/projectmesa/mesa-geo/pull/212#pullrequestreview-2156399161).

**Comment by rht** [comment]
> This is another argument why we need a monorepo (see https://github.com/projectmesa/mesa-geo/pull/212#pullrequestreview-2156399161).

Breaking changes are supposed to be a rare event. This class of errors (of this GH issue) should not have happened that often.

**Comment by jackiekazil** [comment]
That resolved the issue. 

RE: mono repo - the argument against it was that examples were not easily discoverable to people less familiar with repository structures. Originally the examples were in the main repo. 

Unless we explicitly have an action here, I am going close and consider this "resolved" with the next deployment, which I believe will occurring in the near future with recent conversations.
