### ISSUE TITLE
Create example for Ant Colony Optimization

### ISSUE THREAD

**Issue by zjost** [projectmesa/mesa-examples#150]
I'm creating an issue to track this line of work.  One quick question: I am using the latest commit in Mesa to develop (i.e., using `SolaraViz` instead of `JupyterViz`)--is this OK, or should I be doing something different?  Thanks!

**Comment by EwoutH** [comment]
Yes, please develop examples against the latest Mesa alpha release!

See for more background:
- https://github.com/projectmesa/mesa-examples/issues/148

**Comment by EwoutH** [comment]
Closing this issue as completed, since it was merged in #157 thanks a lot Zak!
