### ISSUE TITLE
virus_on_network new visualization doesn't update while running model.

### ISSUE THREAD

**Issue by DrEntropy** [projectmesa/mesa-examples#168]
Virus_on_network doesn't update the visualization (using the new SolaraViz) using the current main branch of mesa.  This is due to SolaraViz watching model._steps which is not updated in this model (it doesn't use a built in schedular).

**Comment by EwoutH** [comment]
You’re correct. I expected https://github.com/projectmesa/mesa/pull/2223 to go through together with that, but it’s taking some longer time than expected (see https://github.com/projectmesa/mesa/discussions/2227).

**Comment by EwoutH** [comment]
I've reverted #161 in #170, could you confirm the visualisation now works again?

Thanks for the feedback by the way, I hope we will resolve the conceptual discussions around time at some point and be able to revert-revert #161 maybe even.

**Comment by DrEntropy** [comment]
Yes I have confirmed that reverting to using schedulers fixes the issue, thanks!
