### ISSUE TITLE
Fix all GIS models

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa-examples#172]
We just started testing our GIS models in CI (see https://github.com/projectmesa/mesa-examples/pull/171), and currently unfortunately all 7 models that are tested present one or multiple errors

The errors are visible in any recent CI run of the [Test GIS models](https://github.com/projectmesa/mesa-examples/actions/workflows/test_gis_examples.yml) workflow. They can also be reproduced and tested locally by running the `test_gis_examples.py` script with pytest.

![image](https://github.com/user-attachments/assets/79b13a25-c647-4a5e-a511-0af9e90fd707)

#### Current errors
- [x] **GeoSchelling**
  - [x] Fix missing file: `data/nuts_rg_60M_2013_lvl_2.geojson`
  - [x] Fix missing Model initialization
  - [x] UserWarning: The weights matrix is not fully connected:
- [x] **GeoSchellingPoints**
  - [x] Fix missing file: `data/nuts_rg_60M_2013_lvl_2.geojson`
- [x] **Rainfall**
  - [x] Fix missing file: `/vsigzip/data/elevation.asc.gz`
  - [x] Fix missing Model initialization
  - [x] RasterLayer doesn't have access to Model ([mesa-geo#236](https://github.com/projectmesa/mesa-geo/issues/236))
- [x] **Population**
  - [x] Fix missing file: `/vsizip/data/clip.zip`
  - [x] Fix missing Model initialization
  - [x] RasterLayer doesn't have access to Model ([mesa-geo#236](https://github.com/projectmesa/mesa-geo/issues/236))
- [x] **AgentsAndNetworks**
  - [x] Provide the following required arguments (6312ebe75af363ce711ce8c07a70830c076e4fd5):
    - [x] `campus`
    - [x] `data_crs`
    - [x] `buildings_file`
    - [x] `walkway_file`
    - [x] `lakes_file`
    - [x] `rivers_file`
    - [x] `driveway_file`
    - [x] `num_commuters`
  - [x] unhashable type error (f24626e4dac359fd3d3c23e3db8e154497140cd8)
  - [x] set output_dir (679b677c42767b78244e89cf34cc1eb8e1c2622a)
- [x] **GeoSir**
  - [x] Fix missing file: `data/TorontoNeighbourhoods.geojson`
  - [x] Fix missing Model initialization
- [x] **UrbanGrowth**
  - [x] Provide missing argument for `RasterLayer.__init__()`: `model`

PRs to fix any of these issues are very welcome!

**Update:**
- The missing geojson paths where fixed in https://github.com/projectmesa/mesa-examples/pull/176
- The missing Model initialization is fixed in https://github.com/projectmesa/mesa-examples/pull/175
- More data paths and model passing: https://github.com/projectmesa/mesa-examples/pull/177
- Pass the model to RasterLayers: https://github.com/projectmesa/mesa-examples/pull/186
- Fix missing default parameters, paths and output_dir: https://github.com/projectmesa/mesa-examples/pull/187
- Fix user warning in GeoSchelling https://github.com/projectmesa/mesa-examples/pull/189

**Comment by EwoutH** [comment]
(help is wanted on all our issues, including the ones without this label, so removing it)

**Comment by EwoutH** [comment]
@wang-boyu Could you add sensible default values to the `AgentsAndNetworks` model?

https://github.com/projectmesa/mesa-examples/blob/3d29e4c215154396e20a5a39a09b8a4043b22de6/gis/agents_and_networks/src/model/model.py#L44

Or maybe load them from:

https://github.com/projectmesa/mesa-examples/blob/3d29e4c215154396e20a5a39a09b8a4043b22de6/gis/agents_and_networks/scripts/run.py#L34

**Comment by EwoutH** [comment]
All warnings resolved! The next thing that needs to happen, is the big backport to the `mesa-2.x` branch, to make sure they're there working, before we update them with Mesa 3.0 stuff.

**Comment by EwoutH** [comment]
The big backport was successful, working, CI tested GIS examples are now available both on the `main` and `mesa-2.x` branches.

Completed! Thanks @wang-boyu!

**Comment by wang-boyu** [comment]
GIS example tests were long overdue. Thanks for your work on this!
