### ISSUE TITLE
ImportError: cannot import name 'SolaraViz' from 'mesa.visualization'

### ISSUE THREAD

**Issue by budennovsk** [projectmesa/mesa-examples#203]
Hello, after updating to the latest #201, the visualization stopped working. I noticed this issue using the example 'https://github.com/projectmesa/mesa-examples/tree/main/examples/hotelling_law'. In the 'app.py' file, the import 'from mesa.visualization import SolaraViz, make_plot_measure' is causing the problem.

**Comment by EwoutH** [comment]
Thanks for reporting a potential issue! Which exact Mesa version are you using?

We also updated the SolaraViz API recently. Please check:
- The [migration guide](https://mesa.readthedocs.io/en/latest/migration_guide.html)
- https://github.com/projectmesa/mesa/pull/2263

**Comment by budennovsk** [comment]
![image](https://github.com/user-attachments/assets/2ecf96d2-1e63-4a57-8f77-60448cb1ccd2)

![image](https://github.com/user-attachments/assets/00f65b6a-dcc4-4538-b2e4-d63f24520b70)

**Comment by budennovsk** [comment]
You are correct, installing version 3.0.0a5 resolved the issue. Thank you!

**Comment by EwoutH** [comment]
Great to hear! Make sure to check out the [migration guide](https://mesa.readthedocs.io/en/latest/migration_guide.html) and [changelog](https://github.com/projectmesa/mesa/blob/main/HISTORY.md), we changed quite a lot.

We're close to a 3.0 beta release, so any feedback on 3.0 and it's documentation is appreciated!

By the way, our old examples for Mesa 2.x are also still available if needed. See https://github.com/projectmesa/mesa-examples/issues/148.
