### ISSUE TITLE
Replace GeoSir scheduler with AgentSet functionality

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa-examples#209]
Currently the GeoSir model has interesting scheduling behavior, where it looks like the Agents are added multiple times to a base schedulers, with all Agents first being added, and then their neighbours again:

https://github.com/projectmesa/mesa-examples/blob/2c05149b4b52b70de77f4dfcbc59f4e3f93c554a/gis/geo_sir/model.py#L32
https://github.com/projectmesa/mesa-examples/blob/2c05149b4b52b70de77f4dfcbc59f4e3f93c554a/gis/geo_sir/model.py#L84-L90
https://github.com/projectmesa/mesa-examples/blob/2c05149b4b52b70de77f4dfcbc59f4e3f93c554a/gis/geo_sir/model.py#L107

The schedulers are deprecated (see https://github.com/projectmesa/mesa/pull/2306), so we would like to replace the BaseScheduler with `AgentSet.do()` operations (as of the [Migration guide](https://mesa.readthedocs.io/latest/migration_guide.html#time-and-schedulers)).

@glicerico, if I'm correct you originally wrote this model. Could you explain exactly what's happening? And would you be interested in updating the example?

**Comment by glicerico** [comment]
@EwoutH i highly doubt I wrote this model, unless my memory has totally forgotten it, hehe... but I also don't appear in the list of contributors.

**Comment by glicerico** [comment]
hahaha seems like it was a mem segfault...  :P  I used this for a short time only.

So, i doubt I can easily help with migration at this point if I didn't even remember I wrote it, sorry!
