### ISSUE TITLE
which python version works with this tutorial?

### ISSUE THREAD

**Issue by pifparfait** [projectmesa/mesa-examples#216]
I’m encountering an issue with a model in Google Colab and would appreciate your help. Specifically, I’m trying to figure out which version of Python is required to execute the following notebook correctly: [Google Colab Mesa-Geo Tutorial](https://colab.research.google.com/github/projectmesa/mesa-geo/blob/main/docs/tutorials/intro_tutorial.ipynb#scrollTo=c181dbf7-c175-47c7-8c20-2ec8fa758c60).

TypeError                                 Traceback (most recent call last)
<ipython-input-12-f0349b3e16d2> in <cell line: 1>()
----> 1 model = GeoSIR()
      2 model.step()

3 frames
/usr/local/lib/python3.10/dist-packages/mesa_geo/geoagent.py in create_agent(self, geometry, unique_id)
    157             raise ValueError("Model must be a valid Mesa model object")
    158 
--> 159         new_agent = self.agent_class(
    160             unique_id=unique_id,
    161             model=self.model,

TypeError: NeighbourhoodAgent.__init__() got an unexpected keyword argument 'unique_id'

 I believe this may be related to a compatibility issue between the Mesa-Geo package and the version of Python being used. Any guidance on which version of Python is best for running this notebook or how to resolve this error would be greatly appreciated.

Thanks in advance for your help!

Best regards,

**Comment by EwoutH** [comment]
It’s not the Python version, but the Mesa / Mesa-gel version. See https://mesa.readthedocs.io/latest/migration_guide.html#automatic-assignment-of-unique-id-to-agents

You are using an older version of the tutorial. I would recommend upgrading to the latest mesa and mesa-geo pre-releases, and then running the latest version of the tutorial https://mesa-geo.readthedocs.io/latest/tutorials/intro_tutorial.html

**Comment by pifparfait** [comment]
Many thanks!
Solved the Mesa/Mesa-geo version for the tutorial!


*Parfait Atchadé*

*Tel Spain: 0034661205543*
*Tel Deutsch: 00491706659017*
