### ISSUE TITLE
The error occurred while running the example "mesa-examples/examples/forest_fire/Forest Fire Model.ipynb".

### ISSUE THREAD

**Issue by weililiuo** [projectmesa/mesa-examples#228]
There are two main errors. The first one occurs when running from mesa.batchrunner import BatchRunner.
![er1](https://github.com/user-attachments/assets/84e83c08-1199-4a3e-bddb-40e63994b8c7)
When I changed the previous error part to import mesa.batchrunner, the program continued to run. However, an error occurred again in the sixth code block.
![er2](https://github.com/user-attachments/assets/b9e04c31-e51f-425b-a366-291d9cb7b7f1)
I'm not sure if these two errors are related, which makes it a bit difficult for me to know how to proceed. I hope someone kind can help me resolve this issue.

**Comment by EwoutH** [comment]
BatchRunner was removed a while ago (in https://github.com/projectmesa/mesa/pull/1689), we replaced it with [batch_run](https://mesa.readthedocs.io/stable/apis/batchrunner.html).

You can either update the example (an PR is appreciated!) or use an older Mesa version, I think [v1.2.0](https://github.com/projectmesa/mesa/releases/tag/v1.2.0) is the latest version that supports the old BatchRunner.

**Comment by weililiuo** [comment]
Thanks for your suggestion, but the second issue is still not resolved. The error shows "'ForestFire' object has no attribute 'dc'." This might be a separate issue?

**Comment by EwoutH** [comment]
It’s probably just `datacollector` instead of `dc`, could you try that?

The answer is in the code :)

**Comment by weililiuo** [comment]
Thanks, the problem is solved! Next time I'll make sure to read the code carefully first...

**Comment by EwoutH** [comment]
No worries, and feel free to open a PR to fix it in our example!
