### ISSUE TITLE
AttributeError: module 'mesa' has no attribute 'visualization'

### ISSUE THREAD

**Issue by weililiuo** [projectmesa/mesa-examples#229]
When I open most of the examples in mesa-examples/gis and run the command "mesa runserver," I get the error "AttributeError: module 'mesa' has no attribute 'visualization'." What could be the reason for this? Thank you for taking the time to look into this issue.

**Comment by EwoutH** [comment]
It probably has to do with the Mesa version you're using. Please see the pinned issue for details:
- https://github.com/projectmesa/mesa-examples/issues/148

**Comment by weililiuo** [comment]
Thank you so much! I believe the work you do helps a lot of people.
