### ISSUE TITLE
WolfSheep example not running

### ISSUE THREAD

**Issue by teshanshanuka** [projectmesa/mesa-examples#5]
Running the WolfSheep example gives error
  ```
File "/home/teshanl/codes/mesa/mesa-examples/examples/WolfSheep/wolf_sheep/server.py", line 44, in <module>
    "WolfSheep", grass=True)
TypeError: __init__() got an unexpected keyword argument 'grass'
``` 

line 43 of file `WolfSheep/wolf_sheep/server.py` must be changed into 
`server = ModularServer(WolfSheepPredation, [canvas_element,  "WolfSheep", model_params={"grass": True})`

Edit: Oh it's wrong in every example. Maybe the `mesa` libraries updated but the examples didn't? 

`ModularServer` is created with parameters for the `Model` as its `args` and `kwargs` but `ModularServer` expects `Model` `kwargs` passed to it as a dictionary to the parameter `model_params`

**Comment by jackiekazil** [comment]
Please see the examples here: https://github.com/projectmesa/mesa/tree/master/examples
