### ISSUE TITLE
data collector not recording agents result and step-by-step results for agents

### ISSUE THREAD

**Issue by wcchin** [projectmesa/mesa-examples#6]
I copied the _schedule.py_ file from the WolfSheep example for a model I am developing with, which has two "breeds" and I need to control the step sequence, something like: all wolf move, then all sheep move. And I find this custom scheduler very useful. (I think maybe this should be added to useful snippet or inside mesa itself?)

But there are two parts are missing, which cause the data collector fail to work properly. 

For making the data collector to work for agents (i.e. get_agent_vars_dataframe()), two parts are needed to be add in the _schedule.py_ file:

1. data collector will record nothing for the agents if the agents list is missing: 

            agents_by_breed = defaultdict(list)
            agents = [] # <-- this line need to be added

2. these two lines:

            for agent in agents:
                agent.step()
            self.steps += 1 # <-- this line and
            self.time += 1  # <-- this line need to be added

are missing in the step_breed(self, breed) method.
This will cause the data collector won't recording step by step results when using the step_breed method. It will record only step=0 results.

Edit: the second part will result in another issue that if call two times for the two breeds, i.e. once for wolf and another for sheep, then the total steps will be double, and the wolf steps are odd numbers and sheep steps are even numbers. So, the two lines should be added to the model:

            self.schedule.steps += 1 
            self.schedule.time += 1

**Comment by jackiekazil** [comment]
Please see the examples here: https://github.com/projectmesa/mesa/tree/master/examples
