### ISSUE TITLE
Attribute error while generating next_id()

### ISSUE THREAD

**Issue by sanketrane** [projectmesa/mesa-examples#7]
I wish to add a new agent with new unique_id (to depict reproduction).
When I set the argument using next_id() I get an error

```
AttributeError: 'MyModel' object has no attribute 'current_id'
```

Simplified code is as follows - 

```
class MyAgent(Agent):
    def __init__(self, unique_id, model):
        super().__init__(unique_id, model)

new_a = MyAgent(self.model.next_id(), self.model)
```
Can anyone help me understand what's going on?
I checked my model.py file in Mesa directory and it has next_id() function defined. 

thanks in advance!

**Comment by JoaoMergulhao** [comment]
Hi @sanketrane! Having the same issue. How did you solve this?

**Comment by EwoutH** [comment]
@sanketrane Since you closed the issue, did you manage to solve it? If so, how?

**Comment by EwoutH** [comment]
Adding
```Python
self.current_id = 0
```
to the model initialisation solves this problem.

**Comment by sanketrane** [comment]
Thanks. I started coding abm in C++ for speed
