### ISSUE TITLE
Error while trying to run Viz_MoneyModel.py: TypeError: __init__() takes from 3 to 5 positional arguments but 7 were given

### ISSUE THREAD

**Issue by ChangyuYan** [projectmesa/mesa-examples#8]
$ ls
MoneyModel.py      Readme.md          Viz_MoneyModel.py  __pycache__/       requirements.txt

$ pwd
/Users/erin/Developer/mesa-examples/examples/Boltzmann_Wealth_Model

$ python3 Viz_MoneyModel.py 
Traceback (most recent call last):
  File "Viz_MoneyModel.py", line 28, in <module>
    server = ModularServer(MoneyModel, [grid, chart], "Money Model", 100, 10, 10)
TypeError: __init__() takes from 3 to 5 positional arguments but 7 were given

**Comment by ChangyuYan** [comment]
Update: 

Through a little debugging, I managed to get it work once I change the last three parameter to a dictionary, `{'N': 100, 'width': 10, 'height': 10}`: 

```python
server = ModularServer(MoneyModel, [grid, chart], "Money Model", {'N': 100, 'width': 10, 'height': 10})
```

**Comment by jackiekazil** [comment]
This looks like something you were writing and not part of the repository. Am I correct? 
And if you were writing this, were you writing it in correctly and there is nothing to fix? Or is there something to fix in the tutorial?

**Comment by jackiekazil** [comment]
I didn't realize I was in this repo. This is a bad repo that hasn't been updated. We intended to move the examples here and never did. You can find the examples here: https://github.com/projectmesa/mesa/tree/master/examples 

I will remove these examples.
