### ISSUE TITLE
Test examples periodically and on commits to mesa `main`

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa-examples#85]
I think the examples should be tested in the following cases:
- [ ] when we change the examples here (against both the latest mesa stable version and mesa `main`)
- [ ] when a commit is pushed to mesa `main`
- [ ] periodically (every week) (against mesa `main` and stable)

We can probably recycle some code from https://github.com/projectmesa/mesa/pull/1956. @rht since you wrote that, would you like to do this?

**Comment by rht** [comment]
> when we change the examples here (against both the latest mesa stable version and mesa main)

The CI in projectmesa/mesa-examples already includes mesa-examples: #82.

>  when a commit is pushed to mesa main

Already covered by https://github.com/projectmesa/mesa/pull/1956

>  periodically (every week) (against mesa main and stable)

I find this redundant to the second checklist item.
